# Generated by Django 5.2.14 on 2026-06-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_model_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('faction', models.CharField(max_length=255)),
                ('pdf', models.CharField(blank=True, max_length=512)),
                ('text', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('tokens', models.JSONField(blank=True, default=list)),
                ('files', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name', 'source_id'],
            },
        ),
    ]
